### ISSUE TITLE
caniusevia.com/docs/download_firmware is missing some keyboards

### ISSUE THREAD

**Issue by oprisnik** [the-via/website#42]
Hey!

It looks like there are keyboards missing from https://www.caniusevia.com/docs/download_firmware 
The last one I see is "mysticworks_wyvern_via.hex" but it is for example not showing any Rama keyboards such as the Rama Kara. Tried with both Chrome and Edge.

I guess this is related how you get the list of firmware files from Github, might be capped to 1000 entries, since https://github.com/the-via/firmware/ shows a message at the top: " Sorry, we had to truncate this directory to 1,000 files. 533 entries were omitted from the list." - and it also ends with the same keyboard [mysticworks_wyvern_via.hex](https://github.com/the-via/firmware/blob/master/mysticworks_wyvern_via.hex)

**Comment by olivia** [comment]
Thanks for the bug report ❤️ It is now fixed in 7225cc64b121f623cec8cc796e5fcbc63622efb0

**Comment by oprisnik** [comment]
Awesome, thanks for fixing it so quickly - and thanks for VIA in general :)
