### ISSUE TITLE
Large empty whitespace <div> above landing-page, support-keyboard page etc

### ISSUE THREAD

**Issue by fzhang13** [the-via/website#43]
![image](https://user-images.githubusercontent.com/35814886/186950082-d974ecd8-0dcf-40aa-9194-c79aaffd1efd.png)
currently when navigating to https://www.caniusevia.com/ on desktop, the website loads with large empty div that pushes all the content down out of initial viewport 

## Primary cause 
when the below div is rendered before the main content div this error occurs
![image](https://user-images.githubusercontent.com/35814886/186950760-2defa4f1-a53d-45d6-b87c-28a9acd2dddd.png)

## Correct behavior:
Should render after 
![image](https://user-images.githubusercontent.com/35814886/186951043-e467a1e9-05ae-42c4-be36-b86635b3de38.png)

## Suggested fix:

removing this `<div style="position: static !important;"></div>` , as it does not seem to break styling functionally on desktop
or set div to load after main content div is loaded in

## Tested Device:
Intel MBP 16 2019
Resolution 2560 x 1440 non Retina display (also occurs on retina displays)
Browser: Chrome Version 104.0.5112.101 (Official Build) (x86_64)

@olivia @wilba

**Comment by olivia** [comment]
I can't find any html that includes the `position: static !important` https://github.com/search?q=repo%3Athe-via%2Fwebsite+position%3A&type=code. Do you happen to have any extensions installed that would be inserting it?

**Comment by fzhang13** [comment]
Could be an extension issue from my side as I no longer see this styling div being applied anymore in the DOM, marking closed. Thanks 👍
