### ISSUE TITLE
Where is the updated source code of the website?

### ISSUE THREAD

**Issue by astrolemonade** [the-via/website#56]
Hey!
Where is the updated source code of the website?
On the website:

![image](https://github.com/the-via/website/assets/35623921/d21b867e-3af8-4398-91c9-ff52f8f490ea)

In the repo:
![image](https://github.com/the-via/website/assets/35623921/5b19d2af-5c33-4194-a668-f89d3c424eab)

**Comment by miccou** [comment]
The list of supported keyboards is dynamically updating during the build.

If you look at `package.json` you'll see the `build` script calls `node scripts/generate-dynamic-content.js` which will fetch the supported keyboards from https://usevia.app/definitions/keyboard_names.json and product a new `.mdx` file.

If you run `yarn start`, then the content generation script will not be run. So if you're debugging or developing, you can run `node scripts/generate-dynamic-content.js` before `yarn start` to see up to date supported keyboards.

Hope this clears it up @astrolemonade.
